import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Diamond, LineChart, Sparkles, Users, Check } from "lucide-react";
export const Route=createFileRoute("/about")({head:()=>({meta:[{title:"About BIZZAG — BE YOUR STYLE."},{name:"description",content:"BIZZAG is a trend-led fashion brand evolving from reseller to original label."}]}),component:About});
function About(){return <div>
<section className="bizzag-hero bizzag-hero--about min-h-[390px] text-white"><div className="relative z-10 mx-auto flex min-h-[390px] max-w-[1400px] items-center px-6"><div className="max-w-[690px]"><p className="eyebrow">ABOUT BIZZAG <span className="ml-3 inline-block h-px w-10 bg-bizzag-orange align-middle"/></p><h1 className="mt-3 text-5xl font-black uppercase leading-[.86] sm:text-7xl">DON'T FOLLOW<br/>THE STYLE.<br/>MAKE YOURS<span className="text-bizzag-orange">.</span></h1><p className="mt-5 max-w-lg text-sm leading-6 text-white/75">BIZZAG is more than a store. It’s a mindset. We bring you the trends, the fits and the culture — so you can express the real you.</p><Link to="/shop" className="btn-base mt-6 bg-white text-black">OUR STORY ↓</Link></div></div></section>

<section className="mx-auto grid max-w-[1400px] gap-8 px-6 py-8 lg:grid-cols-[1fr_1.2fr_1fr]">
<div className="overflow-hidden rounded-lg bg-[#eee]"><img src="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=90" alt="" className="h-full min-h-[360px] w-full object-cover"/></div>
<div className="flex flex-col justify-center px-2 py-4"><p className="eyebrow">OUR STORY</p><h2 className="mt-3 text-4xl font-black uppercase leading-[.95]">FROM TRENDS<br/>TO A BIGGER TOMORROW.</h2><p className="mt-5 text-sm leading-7 text-black/65">BIZZAG started with a simple idea — make trending fashion accessible to everyone. We learn what people actually love, what they wear, and what they come back for.</p><p className="mt-4 text-sm leading-7 text-black/65">Every order, click and preference helps us understand the next step. Today it’s about trends. Tomorrow it’s about creating our own.</p><div className="mt-8 grid grid-cols-3 gap-4 border-t pt-6"><div><b className="text-2xl">2026</b><span className="block text-[10px] font-bold uppercase text-black/45">Established</span></div><div><b className="text-2xl">800+</b><span className="block text-[10px] font-bold uppercase text-black/45">Community</span></div><div><b className="text-2xl">∞</b><span className="block text-[10px] font-bold uppercase text-black/45">Bigger to come</span></div></div></div>
<div className="relative overflow-hidden rounded-lg bg-black"><img src="https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1000&q=90" alt="" className="size-full min-h-[360px] object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><h3 className="text-3xl font-black uppercase leading-[.9]">MORE THAN<br/>CLOTHES.<br/>A COMMUNITY<span className="text-bizzag-orange">.</span></h3></div></div>
</section>

<section className="border-y bg-[#fafafa] py-12"><div className="mx-auto grid max-w-[1100px] gap-8 px-6 sm:grid-cols-2 lg:grid-cols-4">{[[Diamond,"TREND-LED","Always updated with what’s fresh and relevant."],[Users,"FOR EVERYONE","Style isn’t a label. It’s for all of us."],[Sparkles,"QUALITY PICKS","Carefully selected pieces you can trust."],[LineChart,"BUILDING ORIGINALS","Your demand shapes our future designs."]].map(([Icon,title,copy])=>{const I=Icon as typeof Diamond;return <div key={String(title)} className="text-center"><div className="mx-auto grid size-11 place-items-center rounded-lg bg-black text-white"><I className="size-5"/></div><h3 className="mt-4 font-bold">{String(title)}</h3><p className="mt-1 text-sm text-black/50">{String(copy)}</p></div>})}</div></section>

<section className="bg-[#0a0a0a] py-14 text-white"><div className="mx-auto max-w-[1400px] px-6"><p className="eyebrow">OUR JOURNEY</p><h2 className="mt-3 text-4xl font-black uppercase">STILL EARLY.<br/>ALREADY GRATEFUL.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-white/60">From reselling trending pieces to understanding what you actually want — and soon, creating our own. This is just the beginning.</p><div className="mt-10 grid gap-0 md:grid-cols-4">{[["2026","BIZZAG Launch","Started with curated trending products."],["2026","Community Growth","800+ customers and counting."],["2027","BIZZAG Originals","Designing our first official collection."],["BEYOND","A Global Brand","More styles. More stories. Same mindset."]].map(([year,title,copy],i)=><div key={title} className="relative border-t border-white/25 px-5 py-6 first:border-t-0 md:border-t md:first:border-t"><div className="mb-5 grid size-5 place-items-center rounded-full bg-white text-black">{i===0?<Check className="size-3"/>:<span className="size-2 rounded-full bg-white"/>}</div><p className="text-xs font-bold">{year}</p><h3 className="mt-2 font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-white/55">{copy}</p></div>)}</div><Link to="/new-drops" className="btn-base mt-8 bg-white text-black">BE A PART OF IT <ArrowRight className="size-4"/></Link></div></section>
</div>}
