import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Plus } from "lucide-react";
import { BIZZAG_CATEGORIES } from "@/lib/bizzag";
export const Route=createFileRoute("/collections")({head:()=>({meta:[{title:"Collections — BIZZAG"},{name:"description",content:"Explore BIZZAG collections and find what moves you."}]}),component:Collections});
function Collections(){const cards=[...BIZZAG_CATEGORIES,{slug:"all-products",name:"All Products",tagline:"Explore the full BIZZAG rotation.",image:"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=88"}];return <div>
<section className="bizzag-hero bizzag-hero--collections min-h-[300px] text-white"><div className="relative z-10 mx-auto flex min-h-[300px] max-w-[1400px] items-center px-6"><div><p className="eyebrow">COLLECTIONS <span className="ml-3 inline-block h-px w-10 bg-bizzag-orange align-middle"/></p><h1 className="mt-3 text-6xl font-black uppercase leading-[.86]">EXPLORE<br/>YOUR STYLE<span className="text-bizzag-orange">.</span></h1><p className="mt-4 text-sm text-white/75">Different fits. Same mindset.<br/>Find what moves you.</p></div></div></section>
<section className="mx-auto max-w-[1400px] px-6 py-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(c=><Link key={c.slug} to="/shop" className="group relative aspect-[1.65] overflow-hidden rounded-lg bg-black"><img src={c.image} alt="" className="absolute inset-0 size-full object-cover opacity-65 transition duration-500 group-hover:scale-105 group-hover:opacity-80"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white"><h2 className="text-2xl font-black uppercase">{c.name}</h2><p className="mt-1 text-xs text-white/75">{c.tagline}</p><span className="mt-3 inline-flex items-center text-xs font-bold">Explore <ArrowRight className="ml-1 size-3"/></span></div></Link>)}</div></section>
<section className="mx-auto max-w-[1400px] px-6 pb-10"><div className="flex flex-col gap-6 rounded-xl bg-black p-8 text-white md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">BIZZAG ORIGINALS</p><h2 className="mt-2 text-4xl font-black uppercase">FROM TREND<br/>TO ORIGINAL.</h2></div><p className="max-w-md text-sm text-white/65">Today’s trends help us understand what tomorrow’s BIZZAG pieces should look like.</p><Link to="/about" className="btn-base border border-white/40">FOLLOW THE BUILD <ArrowRight className="size-4"/></Link></div></section>
</div>}
