import { createFileRoute } from "@tanstack/react-router";
import { useState, type ChangeEvent, type FormEvent } from "react";
import { Mail, MapPin, MessageCircle, Headphones, Heart, Plus } from "lucide-react";
import { submitContactMessage } from "@/lib/catalog.functions";
import { WhatsAppLink } from "@/components/site/WhatsAppButton";
export const Route=createFileRoute("/contact")({head:()=>({meta:[{title:"Contact BIZZAG"},{name:"description",content:"Questions, suggestions or just want to talk style? BIZZAG is here for you."}]}),component:Contact});
function Contact(){const [form,setForm]=useState({name:"",email:"",phone:"",subject:"",message:""});const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const set=(k:keyof typeof form)=>(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setForm(f=>({...f,[k]:e.target.value}));async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await submitContactMessage({data:form});setSent(true);setForm({name:"",email:"",phone:"",subject:"",message:""})}catch{setError("We could not send your message. Try WhatsApp instead.")}finally{setBusy(false)}}return <div>
<section className="bizzag-hero bizzag-hero--contact min-h-[350px] text-white"><div className="relative z-10 mx-auto flex min-h-[350px] max-w-[1400px] items-center px-6"><div><p className="eyebrow">CONTACT US <span className="ml-3 inline-block h-px w-10 bg-bizzag-orange align-middle"/></p><h1 className="mt-3 text-6xl font-black uppercase leading-[.86]">LET'S<br/>TALK STYLE<span className="text-bizzag-orange">.</span></h1><p className="mt-5 text-sm text-white/75">Got a question, suggestion or just want to say hi?<br/>We’re here for you.</p><div className="mt-7 flex gap-8">{[[MessageCircle,"QUICK REPLIES","We usually respond within a few hours"],[Headphones,"REAL SUPPORT","Talk to a real person"],[Heart,"FOR THE COMMUNITY","Your feedback helps us build BIZZAG"]].map(([I,t,c])=>{const Icon=I as typeof MessageCircle;return <div key={String(t)} className="hidden max-w-[150px] sm:block"><Icon className="size-7"/><p className="mt-3 text-xs font-bold">{String(t)}</p><p className="mt-1 text-[11px] text-white/55">{String(c)}</p></div>})}</div></div></div></section>

<section className="mx-auto grid max-w-[1400px] gap-10 px-6 py-10 lg:grid-cols-[1.05fr_.95fr]">
<div><h2 className="text-2xl font-black uppercase">SEND US A MESSAGE</h2><p className="mt-2 text-sm text-black/55">Fill out the form and we’ll get back to you as soon as possible.</p><form onSubmit={submit} className="mt-6 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><input required value={form.name} onChange={set("name")} placeholder="Your Name" className="bizzag-input"/><input required type="email" value={form.email} onChange={set("email")} placeholder="Your Email" className="bizzag-input"/></div><div className="grid gap-3 sm:grid-cols-2"><input value={form.phone} onChange={set("phone")} placeholder="Your Phone (Optional)" className="bizzag-input"/><input value={form.subject} onChange={set("subject")} placeholder="Select Subject" className="bizzag-input"/></div><textarea required rows={7} value={form.message} onChange={set("message")} placeholder="Tell us how we can help..." className="w-full rounded-lg border border-[#dedede] p-4 text-sm outline-none focus:border-black"/><button disabled={busy} className="btn-base w-full bg-black text-white hover:bg-bizzag-orange">{busy?"SENDING...":"SEND MESSAGE →"}</button>{sent&&<p className="text-sm font-medium text-green-700">Message sent. We’ll get back to you.</p>}{error&&<p className="text-sm text-red-600">{error}</p>}</form></div>
<aside className="border-l border-black/10 pl-0 lg:pl-10"><h2 className="text-2xl font-black uppercase">OTHER WAYS TO REACH US</h2><div className="mt-7 space-y-6">{[[MessageCircle,"WhatsApp","For orders, enquiries and support"],[MessageCircle,"Instagram","@bizzag.style"],[Mail,"Email","irfanahammadj@gmail.com"],[MapPin,"Location","Thiruvananthapuram, Kerala, India"]].map(([I,label,copy])=>{const Icon=I as typeof MessageCircle;return <div key={String(label)} className="flex gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-full bg-black text-white"><Icon className="size-5"/></div><div><h3 className="font-bold">{String(label)}</h3><p className="mt-1 text-sm text-black/55">{String(copy)}</p>{label==="WhatsApp"&&<WhatsAppLink className="mt-2 inline-flex text-xs font-bold text-bizzag-orange">Chat on WhatsApp →</WhatsAppLink>}{label==="Instagram"&&<a className="mt-2 inline-block text-xs font-bold text-bizzag-orange" href="https://instagram.com/bizzag.style" target="_blank" rel="noreferrer">Follow us →</a>}
{label==="Email"&&<a className="mt-2 inline-block text-xs font-bold text-bizzag-orange" href="mailto:irfanahammadj@gmail.com">Email us →</a>}</div></div>})}</div></aside>
</section>

<section className="mx-auto max-w-[1400px] px-6 pb-10"><div className="overflow-hidden rounded-xl bg-[#0d0d0d] p-7 text-white md:flex md:items-center md:justify-between"><div><p className="eyebrow">COMMUNITY</p><h2 className="mt-2 text-3xl font-black uppercase">YOUR OPINION MATTERS.</h2><p className="mt-2 max-w-2xl text-sm text-white/60">Got a product idea? A collaboration in mind? Or just want to show us how you style BIZZAG?</p></div><a href="https://instagram.com/bizzag.style" target="_blank" rel="noreferrer" className="btn-base mt-5 border border-white/40 md:mt-0">SHARE YOUR IDEAS →</a></div></section>

<section className="bizzag-faq mx-auto max-w-[1400px] px-6 pb-14"><div className="flex items-end justify-between"><h2 className="text-2xl font-black uppercase">FREQUENTLY ASKED QUESTIONS</h2><span className="text-xs font-bold">View All →</span></div><div className="mt-4 grid gap-x-10 md:grid-cols-2">{["How can I place an order?","How long does delivery take?","Do you offer Cash on Delivery?","Can I return or exchange a product?"].map(q=><details key={q}><summary className="flex items-center justify-between">{q}<Plus className="size-4"/></summary><p className="pb-5 text-sm leading-6 text-black/55">Message us on WhatsApp for the fastest support, or send the contact form above. We’ll guide you through the next step.</p></details>)}</div></section>
</div>}
