import { createFileRoute } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { productsQuery } from "@/lib/catalog.queries";
import { BIZZAG_CATEGORIES, bizzagFallbackProducts } from "@/lib/bizzag";
import { ProductCard } from "@/components/site/ProductCard";
export const Route=createFileRoute("/new-drops")({loader:({context})=>context.queryClient.ensureQueryData(productsQuery),head:()=>({meta:[{title:"New Drops — BIZZAG"},{name:"description",content:"Fresh BIZZAG arrivals. Limited stock. Don't miss what's next."}]}),component:NewDrops});
function NewDrops(){const {data}=useSuspenseQuery(productsQuery);const products=(data.length?data:bizzagFallbackProducts);const [cat,setCat]=useState("All");const [sort,setSort]=useState("Newest First");const filtered=useMemo(()=>{let x=products.filter(p=>p.newArrival||p.badge==="DROP"||p.badge==="NEW"||p.badge==="LIMITED");if(cat!=="All")x=x.filter(p=>p.category===cat.toLowerCase().replaceAll(" ","-"));if(sort==="Price: Low to High")x=[...x].sort((a,b)=>a.price-b.price);if(sort==="Price: High to Low")x=[...x].sort((a,b)=>b.price-a.price);return x.slice(0,24)},[products,cat,sort]);return <div>
<section className="bizzag-hero bizzag-hero--drops min-h-[340px] text-white"><div className="relative z-10 mx-auto flex min-h-[340px] max-w-[1400px] items-center px-6"><div><p className="eyebrow">NEW DROPS <span className="ml-3 inline-block h-px w-10 bg-bizzag-orange align-middle"/></p><h1 className="mt-3 text-6xl font-black uppercase leading-[.86]">FRESH FITS.<br/>BOLDER DAYS<span className="text-bizzag-orange">.</span></h1><p className="mt-4 text-sm text-white/75">Latest arrivals. Limited stock.<br/>Don’t miss what’s next.</p></div></div></section>
<section className="border-b border-black/10 py-5"><div className="mx-auto flex max-w-[1400px] gap-3 overflow-x-auto px-6">{["All",...BIZZAG_CATEGORIES.slice(0,8).map(c=>c.name)].map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-xs font-semibold ${cat===c?"bg-black text-white":"bg-[#f2f2f2]"}`}>{c}</button>)}</div></section>
<section className="mx-auto max-w-[1400px] px-6 py-8"><div className="mb-6 flex items-center justify-between"><p className="text-sm font-bold">{filtered.length} products</p><label className="flex items-center gap-2 text-xs">Sort by <select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-lg border bg-white px-3 py-2 outline-none"><option>Newest First</option><option>Price: Low to High</option><option>Price: High to Low</option></select></label></div><div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!filtered.length&&<div className="py-20 text-center text-sm text-black/45">No new drops in this category yet.</div>}</section>
</div>}
