DELETE FROM public.products WHERE slug IN ('eternal-love-box','golden-memory-frame','cute-hoodie-keychains','miniature-die-cast-cars','retro-sound-box','personalized-photo-lamp','gift-hamper-classic','rose-heart-locket');

INSERT INTO public.products (slug,name,blurb,description,price,mrp,category,badge,rating,reviews,image,images,features,specs,sort_order,sku,stock_status,stock_qty,trending,new_arrival,best_seller,featured,options) VALUES
('shadow-core-tee','Shadow Core Tee','Heavy everyday oversized tee.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',699,944,'t-shirts','TRENDING',4.7,0,'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,1,'BZ-SHADOW-CORE-TEE','in_stock',20,true,false,true,true,'[]'::jsonb),
('urban-classic-shirt','Urban Classic Shirt','Relaxed shirt for clean rotations.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',899,1214,'shirts','NEW',4.7,0,'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,2,'BZ-URBAN-CLASSIC-SHIRT','in_stock',20,false,true,false,false,'[]'::jsonb),
('core-cargo-pants','Core Cargo Pants','Utility pockets. Easy movement.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',1199,1619,'bottomwear','BESTSELLER',4.7,0,'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,3,'BZ-CORE-CARGO-PANTS','in_stock',20,false,false,true,false,'[]'::jsonb),
('street-runner-v1','Street Runner V1','Everyday sneakers with a bold profile.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',1999,2699,'footwear','NEW',4.7,0,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,4,'BZ-STREET-RUNNER-V1','in_stock',20,false,true,false,false,'[]'::jsonb),
('retro-jersey','Retro Jersey','Football energy, BIZZAG attitude.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',899,1214,'jerseys','DROP',4.7,0,'https://images.unsplash.com/photo-1526232761682-d26e03ac9e6b?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1526232761682-d26e03ac9e6b?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,5,'BZ-RETRO-JERSEY','in_stock',20,false,true,false,false,'[]'::jsonb),
('minimal-cap','Minimal Cap','Low-key branding. Easy finish.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',499,674,'accessories','LIMITED',4.7,0,'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,6,'BZ-MINIMAL-CAP','in_stock',20,true,false,false,false,'[]'::jsonb),
('bold-frame-sunglasses','Bold Frame Sunglasses','Statement frames for the daily fit.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',799,1079,'eyewear',NULL,4.7,0,'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,7,'BZ-BOLD-FRAME-SUNGLASSES','in_stock',20,false,false,false,false,'[]'::jsonb),
('signature-hoodie','Signature Hoodie','Heavy layer for after-dark fits.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',1199,1619,'oversized','NEW',4.7,0,'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,8,'BZ-SIGNATURE-HOODIE','in_stock',20,false,true,false,false,'[]'::jsonb),
('classic-chronograph','Classic Chronograph','Clean metal finish. Built to last.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',1599,2159,'watches','LIMITED',4.7,0,'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,9,'BZ-CLASSIC-CHRONOGRAPH','in_stock',20,false,false,false,false,'[]'::jsonb),
('washed-street-shirt','Washed Street Shirt','Texture-led overshirt with a relaxed cut.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',999,1349,'shirts',NULL,4.7,0,'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,10,'BZ-WASHED-STREET-SHIRT','in_stock',20,false,true,false,false,'[]'::jsonb),
('statement-back-print-tee','Statement Back Print Tee','Same people. New standards.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',699,944,'t-shirts','TRENDING',4.7,0,'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,11,'BZ-STATEMENT-BACK-PRINT-TEE','in_stock',20,true,false,false,false,'[]'::jsonb),
('urban-sling-bag','Urban Sling Bag','Compact carry for the daily rotation.','A BIZZAG piece selected for everyday rotation. Built for comfort, movement and personal style.',999,1349,'accessories','NEW',4.7,0,'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=88','{"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=88"}','{"Everyday fit","Easy to style","India-ready pricing"}','[{"label":"Fit","value":"Regular"},{"label":"Care","value":"Machine wash"}]'::jsonb,12,'BZ-URBAN-SLING-BAG','in_stock',20,false,true,false,false,'[]'::jsonb)
ON CONFLICT (slug) DO NOTHING;